version: 0.1
volumeMounts:
  - name: automated-email-credentials
    localPath: /tmp/etc/secret-volume/automated-email-credentials
  - name: af-s3-secrets
    localPath: /tmp/etc/secret-volume/af-s3-secrets
  - name: access-token-public-keys 
    localPath: /tmp/etc/secret-volume/access-token-public-keys
env:
  - name: SECRET_FOLDER_PATH
    value: /tmp/etc/secret-volume
  - name: AUTOMATED_EMAIL_CREDENTIALS_PATH
    value: $(volumeMounts:automated-email-credentials)
  - name: AF_S3_SECRETS_PATH
    value: $(volumeMounts:af-s3-secrets)
  - name: ACCESS_TOKEN_PUBLIC_KEYS_PATH
    value: $(volumeMounts:access-token-public-keys)
  - name: AUTH_APP_SERVICE_SERVICE_HOST
    value: $(services:auth-app-service)
  - name: AUTH_APP_SERVICE_SERVICE_PORT
    value: 8080
  - name: ACCOUNT_APP_SERVICE_SERVICE_HOST
    value: $(services:account-app)
  - name: ACCOUNT_APP_SERVICE_SERVICE_PORT
    value: 8080
